export const QuestionTags =[
	"EC2",
	"Lambda",
	"Cloud Concepts",
	"AWS Infrastructure",
	"Core Services",
	"Storage",
	"Compute",
	"Database",
	"Networking",
	"Security",
	"Compliance",
	"IAM",
	"Pricing",
	"Billing",
	"Architectural Principles",
	"Well-Architected Framework",
	"Support Plans",
	"Trusted Advisor",
	"Deployment Services",
	"CloudFormation",
	"Elastic Beanstalk",
	"OpsWorks",
	"Monitoring",
	"Logging",
	"Performance Optimization",
	"Scalability",
	"Fault Tolerance",
	"Disaster Recovery",
	"High Availability",
	"Cost Management",
	"Resource Optimization",
	"Best Practices"
]
