name: Run build

on: push

permissions:
    id-token: write
    contents: read

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2

            - name: Install dependencies
              run: npm install

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  audience: sts.amazonaws.com
                  aws-region: ${{ secrets.AWS_REGION }}
                  role-to-assume: arn:aws:iam::339713106432:role/GitHub-OpenConnet

            - name: Determine branch name
              id: determine-branch
              run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

            - name: Run amplify outputs
              run: npx ampx generate outputs  --app-id ${{ secrets.AMPLIFY_APP_ID }}

            - name: Run build
              run: npx next build
